### PR TITLE
PWEB-5866 - Remove reverse listener when the key is deleted

### PR DESCRIPTION
**Pull request by neitzj**

### CODE REVIEW

**Comment by jarabek** [comment]
+1

**Comment by jarabek** [comment]
This is good, but I think to fully address the issue, you should also trigger a DetachStorageListener on the key being removed.  You might also want to call that and your removeValueChangeHandler lines before you actually remove the key (this seems unlikely to cause an issue, but that way it definitely wont).

**Comment by neitzj** [comment]
I've now added the DetachStorageListener command

**Comment by jarabek** [comment]
+1

**Pull request merged**
